import { WorryProps } from '@components/Worries/Worries';
import uuid from 'react-native-uuid';
import { getDate } from '@lib/util/date';

export const WORRIES_DATA: WorryProps[] = [
  {
    id: '-1',
    title: getDate(new Date(), 'MM/dd'),
    content: '모든걱정',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: '-1',
    title: getDate(new Date(), 'MM/dd'),
    content: '모든걱정',
    isOpen: false,
    isDone: true,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '경제',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '경제',
    isOpen: false,
    isDone: true,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '진로',
    isOpen: true,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '학업',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '관계',
    isOpen: true,
    isDone: true,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '가족',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '기타',
    isOpen: true,
    isDone: true,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '경제',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '진로',
    isOpen: false,
    isDone: true,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '학업',
    isOpen: true,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '관계',
    isOpen: true,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '직장',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '가족',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '진로',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '경제',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
];
