import { WorryTempProps } from '~/types/Worry';

import uuid from 'react-native-uuid';

export const TAG_RECENT_DATA: WorryTempProps[] = [
  {
    id: uuid.v4(),
    worryId: -1,
    categoryName: '모든걱정',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },

  {
    id: uuid.v4(),
    worryId: 1,
    categoryName: '진로',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 2,
    categoryName: '관계',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 3,
    categoryName: '직장',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 4,
    categoryName: '경제',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 5,
    categoryName: '학업',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 6,
    categoryName: '가족',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 7,
    categoryName: '건강',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 8,
    categoryName: '기타',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
];

export const TAG_PAST_DATA: WorryTempProps[] = [
  {
    id: uuid.v4(),
    worryId: -1,
    categoryName: '모든걱정',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: -2,
    categoryName: '의미있는 걱정',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: true,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: -3,
    categoryName: '의미없는 걱정',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: true,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 1,
    categoryName: '진로',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 2,
    categoryName: '관계',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 3,
    categoryName: '직장',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 4,
    categoryName: '경제',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 5,
    categoryName: '학업',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 6,
    categoryName: '가족',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 7,
    categoryName: '건강',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    worryId: 8,
    categoryName: '기타',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
];
