import { WorryProps, WorryTempProps } from '@components/Worries/Worries';
import uuid from 'react-native-uuid';
import { getDate } from '~/lib/util/date';

export const TAG_DATA: WorryTempProps[] = [
  {
    worryId: -1,
    categoryName: '모든걱정',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    worryId: -2,
    categoryName: '의미있는 걱정',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: true,
    isChecked: false,
  },
  {
    worryId: -3,
    categoryName: '의미없는 걱정',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: true,
    isChecked: false,
  },
  {
    worryId: 1,
    categoryName: '진로',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    worryId: 2,
    categoryName: '관계',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    worryId: 3,
    categoryName: '직장',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    worryId: 4,
    categoryName: '경제',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    worryId: 5,
    categoryName: '학업',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    worryId: 6,
    categoryName: '가족',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    worryId: 7,
    categoryName: '건강',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
  {
    worryId: 8,
    categoryName: '기타',
    worryStartDate: '',
    worryExpiryDate: '',
    locked: false,
    realized: false,
    finished: false,
    isChecked: false,
  },
];

export const WORRIES_DATA: WorryProps[] = [
  {
    id: '-1',
    title: getDate(new Date(), 'MM/dd'),
    content: '모든걱정',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: '-1',
    title: getDate(new Date(), 'MM/dd'),
    content: '모든걱정',
    isOpen: false,
    isDone: true,
    isChecked: false,
  },
  {
    id: uuid,
    title: getDate(new Date(), 'MM/dd'),
    content: '경제',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '경제',
    isOpen: false,
    isDone: true,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '진로',
    isOpen: true,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '학업',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '관계',
    isOpen: true,
    isDone: true,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '가족',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '기타',
    isOpen: true,
    isDone: true,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '경제',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '진로',
    isOpen: false,
    isDone: true,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '학업',
    isOpen: true,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '관계',
    isOpen: true,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '직장',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '가족',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '진로',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
  {
    id: uuid.v4(),
    title: getDate(new Date(), 'MM/dd'),
    content: '경제',
    isOpen: false,
    isDone: false,
    isChecked: false,
  },
];
